name: Deploy DEV

on:
  push:
    branches:
      - dev

jobs:
  deploy:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:

      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.DEV_WIF_PROVIDER }}
          service_account: ${{ secrets.DEV_SERVICE_ACCOUNT }}

      - uses: google-github-actions/setup-gcloud@v2

      - run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev

      - run: |
          docker build -t flask-app .

      - run: |
          docker tag flask-app asia-south1-docker.pkg.dev/${{ secrets.DEV_PROJECT_ID }}/dev-repo/flask-app:${{ github.sha }}

      - run: |
          docker push asia-south1-docker.pkg.dev/${{ secrets.DEV_PROJECT_ID }}/dev-repo/flask-app:${{ github.sha }}

      - run: |
          gcloud run deploy dev-service \
          --image asia-south1-docker.pkg.dev/${{ secrets.DEV_PROJECT_ID }}/dev-repo/flask-app:${{ github.sha }} \
          --region asia-south1 \
          --platform managed \
          --allow-unauthenticated
